version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - pip install -r requirements.txt

  run:
    desc: Run the API locally
    cmds:
      - python main.py

  dev:
    desc: Run with auto-reload
    cmds:
      - uvicorn main:app --reload --port 8080

  clean:
    desc: Clean cache files
    cmds:
      - rm -rf __pycache__ .pytest_cache

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t mjolnir-example-python .

  docker:run:
    desc: Run Docker container
    cmds:
      - docker run --rm -p 8080:8080 mjolnir-example-python
