version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - bun install

  dev:
    desc: Run in development mode with hot reload
    cmds:
      - bun run --watch src/index.ts

  run:
    desc: Run the API locally
    cmds:
      - bun run src/index.ts

  build:
    desc: Build standalone executable
    cmds:
      - bun build src/index.ts --compile --outfile dist/server

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist node_modules

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t mjolnir-example-typescript .

  docker:run:
    desc: Run Docker container
    cmds:
      - docker run --rm -p 8080:8080 mjolnir-example-typescript
